// Replace this file with the firebase_options.dart generated by `flutterfire configure`
// or fill FirebaseOptions manually.
class DefaultFirebaseOptions {
  static get currentPlatform => throw UnimplementedError('Replace with your FirebaseOptions');
}
